<?php

namespace MainBundle\Repository;

/**
 * LikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeRepository extends \Doctrine\ORM\EntityRepository
{
  public function getCountPostLikesIDResult($id_post) {
    $qb = $this->createQueryBuilder('l');
    $qb
      ->select('COUNT (l) AS like_count')
      ->where('l.post = :id_post')
      ->setParameter('id_post', $id_post);

    return $qb->getQuery()->getResult();
  }

  public function checkUserPostLikeResult($id_post, $id_user) {
    $qb = $this->createQueryBuilder('l');
    $qb
      ->where('l.post = :idPost')
      ->andWhere('l.user = :idUser')
      ->setParameter('idPost', $id_post)
      ->setParameter('idUser', $id_user);
    return $qb->getQuery()->getResult();
  }
}
