<?php

namespace MainBundle\Repository;

/**
 * LikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeRepository extends \Doctrine\ORM\EntityRepository
{
  public function getCountByPost($id_post) {
    return (int) $this->createQueryBuilder('l')
      ->select('COUNT (l)')
      ->where('l.post = :id_post')
      ->setParameter('id_post', $id_post)
      ->getQuery()
      ->getSingleScalarResult()
    ;
  }
}
